/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author R-one
 */
public class MainFrame extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement statement = null;
    private Database db;


    public MainFrame() {
        initComponents();
        db = new Database();
        conn = db.CreateDBConnection();
        currentDate();
    }
    
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSED);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    
    public void currentDate()
    {
        Thread clock = new Thread(){
        public void run()
        {
        for(;;) 
        {        
        Calendar cal = new GregorianCalendar();
        int year = cal.get(Calendar.YEAR);
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        txt_date.setText("Date: "+day+ "-"+(month+1)+"-"+year);
        
        int hour = cal.get(Calendar.HOUR);
        int minute = cal.get(Calendar.MINUTE);
        int second = cal.get(Calendar.SECOND);
        txt_time.setText("Time: "+hour+ ":"+(minute)+":"+second);
        
            try 
            {
                sleep(1000);
            } catch (InterruptedException ex)
            {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
               
        }
        }
      
        };        
       clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        cmd_branch_info = new javax.swing.JButton();
        cmd_product_issue_info = new javax.swing.JButton();
        cmd_current_stock_info = new javax.swing.JButton();
        cmd_company_info = new javax.swing.JButton();
        cmd_sales_info = new javax.swing.JButton();
        cmd_daily_expense = new javax.swing.JButton();
        cmd_product_info = new javax.swing.JButton();
        cmd_petty_cash = new javax.swing.JButton();
        cmd_local_purchase = new javax.swing.JButton();
        cmd_monthly_sales_report = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmd_foto_world_petty_cash = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        shutdown_pc = new javax.swing.JMenuItem();
        internet_connection = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Window", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        cmd_branch_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_branch_info.setForeground(new java.awt.Color(51, 51, 255));
        cmd_branch_info.setText("Branch Info");
        cmd_branch_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_branch_infoActionPerformed(evt);
            }
        });

        cmd_product_issue_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_product_issue_info.setForeground(new java.awt.Color(51, 51, 255));
        cmd_product_issue_info.setText("Product Issue Info");
        cmd_product_issue_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_product_issue_infoActionPerformed(evt);
            }
        });

        cmd_current_stock_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_current_stock_info.setForeground(new java.awt.Color(51, 51, 255));
        cmd_current_stock_info.setText("Current Stock Info");
        cmd_current_stock_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_current_stock_infoActionPerformed(evt);
            }
        });

        cmd_company_info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_company_info.setForeground(new java.awt.Color(51, 51, 255));
        cmd_company_info.setText("Company Info");
        cmd_company_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_company_infoActionPerformed(evt);
            }
        });

        cmd_sales_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_sales_info.setForeground(new java.awt.Color(51, 51, 255));
        cmd_sales_info.setText("Branch Sales Info");
        cmd_sales_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_sales_infoActionPerformed(evt);
            }
        });

        cmd_daily_expense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_daily_expense.setForeground(new java.awt.Color(51, 51, 255));
        cmd_daily_expense.setText("Daily Expense");
        cmd_daily_expense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_daily_expenseActionPerformed(evt);
            }
        });

        cmd_product_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_product_info.setForeground(new java.awt.Color(51, 51, 255));
        cmd_product_info.setText("Product Info");
        cmd_product_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_product_infoActionPerformed(evt);
            }
        });

        cmd_petty_cash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_petty_cash.setForeground(new java.awt.Color(51, 51, 255));
        cmd_petty_cash.setText("Petty Cash");
        cmd_petty_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_petty_cashActionPerformed(evt);
            }
        });

        cmd_local_purchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_local_purchase.setForeground(new java.awt.Color(51, 51, 255));
        cmd_local_purchase.setText("Local purchase Info");
        cmd_local_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_local_purchaseActionPerformed(evt);
            }
        });

        cmd_monthly_sales_report.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_monthly_sales_report.setForeground(new java.awt.Color(51, 51, 255));
        cmd_monthly_sales_report.setText("Monthly Sales Report");
        cmd_monthly_sales_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_monthly_sales_reportActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Branch Stock Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmd_foto_world_petty_cash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_foto_world_petty_cash.setForeground(new java.awt.Color(51, 51, 255));
        cmd_foto_world_petty_cash.setText("Foto World Petty Cash");
        cmd_foto_world_petty_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_foto_world_petty_cashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmd_monthly_sales_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_product_issue_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_company_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_current_stock_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_branch_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_sales_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_petty_cash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_product_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_daily_expense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_local_purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_foto_world_petty_cash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_company_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_product_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_branch_info, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_product_issue_info, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_sales_info, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_daily_expense, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_current_stock_info, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_petty_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_local_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmd_monthly_sales_report, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmd_foto_world_petty_cash))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("WELCOME TO FUJI LAB");

        txt_time.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_time.setForeground(new java.awt.Color(51, 51, 255));

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_date.setForeground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("INVENTORY MANAGEMENT SYSTEM");

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("New");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        shutdown_pc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        shutdown_pc.setText("Shutdown");
        shutdown_pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdown_pcActionPerformed(evt);
            }
        });
        jMenu1.add(shutdown_pc);

        internet_connection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        internet_connection.setText("Internet Connection");
        internet_connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internet_connectionActionPerformed(evt);
            }
        });
        jMenu1.add(internet_connection);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(255, 255, 255)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(295, 295, 295)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(989, 667));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_product_issue_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_product_issue_infoActionPerformed
        // TODO add your handling code here:
        ProductIssueToBranchInfoJFrame pbf = new ProductIssueToBranchInfoJFrame();
        pbf.setVisible(true);
        
    }//GEN-LAST:event_cmd_product_issue_infoActionPerformed

    private void cmd_company_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_company_infoActionPerformed
        // TODO add your handling code here:
        CompanyInfoJFrame cf = new CompanyInfoJFrame();
        cf.setVisible(true);
        
    }//GEN-LAST:event_cmd_company_infoActionPerformed

    private void cmd_branch_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_branch_infoActionPerformed
        // TODO add your handling code here:
        BranchInfoFrame bf = new BranchInfoFrame();
        bf.setVisible(true);
    }//GEN-LAST:event_cmd_branch_infoActionPerformed

    private void cmd_product_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_product_infoActionPerformed
        // TODO add your handling code here:
        ProductInfoJFrame pf = new ProductInfoJFrame();
        pf.setVisible(true);
    }//GEN-LAST:event_cmd_product_infoActionPerformed

    private void cmd_sales_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_sales_infoActionPerformed
        // TODO add your handling code here:
        SalesInfoJFrame sif = new SalesInfoJFrame();
        sif.setVisible(true);
        
    }//GEN-LAST:event_cmd_sales_infoActionPerformed

    private void cmd_daily_expenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_daily_expenseActionPerformed
        // TODO add your handling code here:
        DailyExpenseJFrame def = new DailyExpenseJFrame();
        def.setVisible(true);
        
        
    }//GEN-LAST:event_cmd_daily_expenseActionPerformed

    private void cmd_current_stock_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_current_stock_infoActionPerformed
        //TODO add your handling code here:
        CurrentStockInfoJFrame csf = new CurrentStockInfoJFrame();
        csf.setVisible(true);
    }//GEN-LAST:event_cmd_current_stock_infoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void shutdown_pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdown_pcActionPerformed
        // TODO add your handling code here:
        Runtime runtime = Runtime.getRuntime();
        try
        {
            wait(10);
            Process proc = runtime.exec("shutdown -s -t 0");
            
        }catch(Exception ex)
        {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_shutdown_pcActionPerformed

    private void internet_connectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internet_connectionActionPerformed
        // TODO add your handling code here:
     
       
    }//GEN-LAST:event_internet_connectionActionPerformed

    private void cmd_petty_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_petty_cashActionPerformed
        // TODO add your handling code here:
        PettyCash pc = new PettyCash();
        pc.setVisible(true);
        
    }//GEN-LAST:event_cmd_petty_cashActionPerformed

    private void cmd_local_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_local_purchaseActionPerformed
        // TODO add your handling code here:
        LocalPurchaseFrame lp = new LocalPurchaseFrame();
        lp.setVisible(true);
        
   
        
    }//GEN-LAST:event_cmd_local_purchaseActionPerformed

    private void cmd_monthly_sales_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_monthly_sales_reportActionPerformed
        // TODO add your handling code here:
        MonthlySalesReportJFrame msr = new MonthlySalesReportJFrame();
        msr.setVisible(true);
        
    }//GEN-LAST:event_cmd_monthly_sales_reportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BranchStockJFrame bs = new BranchStockJFrame();
        bs.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmd_foto_world_petty_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_foto_world_petty_cashActionPerformed
        // TODO add your handling code here:
        PhotoWorldJFrame fw = new PhotoWorldJFrame();
        fw.setVisible(true);
    }//GEN-LAST:event_cmd_foto_world_petty_cashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_branch_info;
    private javax.swing.JButton cmd_company_info;
    private javax.swing.JButton cmd_current_stock_info;
    private javax.swing.JButton cmd_daily_expense;
    private javax.swing.JButton cmd_foto_world_petty_cash;
    private javax.swing.JButton cmd_local_purchase;
    private javax.swing.JButton cmd_monthly_sales_report;
    private javax.swing.JButton cmd_petty_cash;
    private javax.swing.JButton cmd_product_info;
    private javax.swing.JButton cmd_product_issue_info;
    private javax.swing.JButton cmd_sales_info;
    private javax.swing.JMenuItem internet_connection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem shutdown_pc;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables
}
