/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;


public class ProductIssueToBranchInfoJFrame extends javax.swing.JFrame {

 Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement statement = null;
     private Database db;
     //ProductInfoJFrame pif = new ProductInfoJFrame();
    
     
    public ProductIssueToBranchInfoJFrame() {
        initComponents();
        db = new Database();
        conn = db.CreateDBConnection();
    }
    
     private void Update_table()
    {
        try{
        String sql = "select * from prod_issue_to_branch_info";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        product_issue_table.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }
     
       private void clear()
 {
     txt_issueno.setText("");
     txt_issuedate.getDateFormatString();
     txt_issuefrom.setText("");
     txt_issue_from_address.setText("");
     txt_issueto.setText("");
     txt_issue_to_address.setText("");
     txt_productcode.setText("");
     txt_productname.setText("");
     txt_unitprice.setText("");
     //txt_stockquantity.setText("");
     txt_issuequantity.setText("");
   
     
     
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_issue_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_issuequantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_issue_to_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_productname = new javax.swing.JTextField();
        txt_issueno = new javax.swing.JTextField();
        txt_issue_from_address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmd_product_issue = new javax.swing.JButton();
        txt_productcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_issueto = new javax.swing.JTextField();
        txt_issuefrom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_unitprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmd_show_issue_product = new javax.swing.JButton();
        txt_issuedate = new com.toedter.calendar.JDateChooser();
        cmd_back = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        cmd_delete = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Product Issue To Branch Information");

        product_issue_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        product_issue_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_issue_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(product_issue_table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daily Product Issue Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel8.setText("Product Name:");

        jLabel11.setText("Unit Price:");

        jLabel2.setText("Issue No:");

        jLabel4.setText("Issue From Address:");

        jLabel9.setText("Product Code:");

        jLabel7.setText("Issue To:");

        jLabel12.setText("Issue Quantity:");

        cmd_product_issue.setText("Product Issue");
        cmd_product_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_product_issueActionPerformed(evt);
            }
        });

        jLabel5.setText("Issue Date:");

        jLabel6.setText("Issue To Address:");

        jLabel3.setText("Issue From:");

        cmd_show_issue_product.setText("Show Issue Product");
        cmd_show_issue_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_show_issue_productActionPerformed(evt);
            }
        });

        txt_issuedate.setDateFormatString("yyyy-MM-dd");

        cmd_back.setText("<< Back");
        cmd_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_backActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmd_delete.setText("Delete");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_update.setText("Update");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_productcode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_issuedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_issuefrom)
                            .addComponent(txt_issueno)
                            .addComponent(txt_issue_from_address)
                            .addComponent(txt_issueto)
                            .addComponent(txt_issue_to_address)
                            .addComponent(txt_unitprice)
                            .addComponent(txt_issuequantity)
                            .addComponent(txt_productname)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmd_product_issue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmd_show_issue_product, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmd_clear))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cmd_back, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmd_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmd_update, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_issueno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_issuefrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_issue_from_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_issueto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_issue_to_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_productcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_issuequantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_show_issue_product)
                    .addComponent(cmd_product_issue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_delete)
                    .addComponent(cmd_clear)
                    .addComponent(jButton1))
                .addGap(132, 132, 132))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypkg/Fuji_logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1167, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void product_issue_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_issue_tableMouseClicked
        // TODO add your handling code here:
         try
        {
            int row = product_issue_table.getSelectedRow();
            String table_click = (product_issue_table.getModel().getValueAt(row, 0).toString());
            String sql = "select * from  prod_issue_to_branch_info where issue_no = '"+table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next())
            {
                String add1 = rs.getString("issue_no");
                txt_issueno.setText(add1);
                
                String add2 = rs.getString("issue_date");
                txt_issuedate.setDateFormatString(add2);
                
                String add3 = rs.getString("issue_from");
                txt_issuefrom.setText(add3);
                
                String add4 = rs.getString("issue_from_add");
                txt_issue_from_address.setText(add4);
                
                String add5 = rs.getString("issue_to");
                txt_issueto.setText(add5);
                
                String add6 = rs.getString("issue_to_address");
                txt_issue_to_address.setText(add6);
                
                String add7 = rs.getString("product_code");
                txt_productcode.setText(add7);
                
                
                String add8 = rs.getString("product_name");
                txt_productname.setText(add8);
                
                String add9 = rs.getString("unit_price");
                txt_unitprice.setText(add9);
                
                String add10 = rs.getString("issue_quantity");
                txt_issuequantity.setText(add10);
                
               
                
                
                
            }
            
        }catch(Exception e )
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_product_issue_tableMouseClicked

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
        try
        {
            String issue_no = txt_issueno.getText();
            String issue_date = txt_issuedate.getDateFormatString();
            String issue_from = txt_issuefrom.getText();
            String issue_from_add = txt_issue_from_address.getText();
            String issue_to = txt_issueto.getText();
            String issue_to_address = txt_issue_to_address.getText();
            String product_code = txt_productcode.getText();
            String product_name = txt_productname.getText();
            String unit_price = txt_unitprice.getText();
            String issue_quantity = txt_issuequantity.getText();

            //Update query
            String sql = "update prod_issue_to_branch_info set issue_date = '"+issue_date+"', issue_from = '"+issue_from+"', issue_from_add = '"+issue_from_add+"', issue_to = '"+issue_to+"', issue_to_address = '"+issue_to_address+"', product_code = '"+product_code+"', product_name = '"+product_name+"', unit_price = '"+unit_price+"', issue_quantity = '"+issue_quantity+"' where issue_no = '"+issue_no+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Updated");
            clear();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();

    }//GEN-LAST:event_cmd_updateActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql = "delete from prod_issue_to_branch_info where issue_no = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_issueno.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
            clear();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_backActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);

    }//GEN-LAST:event_cmd_backActionPerformed

    private void cmd_show_issue_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_show_issue_productActionPerformed
        // TODO add your handling code here:
        Update_table();
    }//GEN-LAST:event_cmd_show_issue_productActionPerformed

    private void cmd_product_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_product_issueActionPerformed
        // TODO add your handling code here:
        String issue_no = txt_issueno.getText();
        String issue_date = txt_issuedate.getDateFormatString();
        String issue_from = txt_issuefrom.getText();
        String issue_from_add = txt_issue_from_address.getText();
        String issue_to = txt_issueto.getText();
        String issue_to_address = txt_issue_to_address.getText();
        String product_code = txt_productcode.getText();
        String product_name = txt_productname.getText();
        String unit_price = txt_unitprice.getText();
        String issue_quantity = txt_issuequantity.getText();

        if(issue_no.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue no can not be empty");
        }
        else if(issue_date.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue date can not be empty");
        }
        else if(issue_from.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue from can not be empty");
        }
        else if(issue_from_add.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue from address can not be empty");
        }
        else if(issue_to.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue to can not be empty");
        }
        else if(issue_to_address.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue to address can not be empty");
        }
        else if(product_code.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Product code can not be empty");
        }
        else if(product_name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Product name can not be empty");
        }
        else if(unit_price.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Unit price can not be empty");
        }
        else if(issue_quantity.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Issue quantity can not be empty");
        }

        else
        {
            //call database value
            //String p_qunatity = "select quantity from product_info where product_code = '"+product_code+"'";

            //int tem_quantity = Integer.parseInt(p_qunatity)- Integer.parseInt(issue_quantity);

            //if( Integer.parseInt(p_qunatity) >= Integer.parseInt(issue_quantity))
            try
            {
                String sql = "insert into prod_issue_to_branch_info(issue_no, issue_date, issue_from, issue_from_add, issue_to, issue_to_address, product_code, product_name, unit_price, issue_quantity) values(?,?,?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_issueno.getText());
                pst.setString(2, ((JTextField)txt_issuedate.getDateEditor().getUiComponent()).getText());
                pst.setString(3, txt_issuefrom.getText());
                pst.setString(4, txt_issue_from_address.getText());
                pst.setString(5, txt_issueto.getText());
                pst.setString(6, txt_issue_to_address.getText());
                pst.setString(7, txt_productcode.getText());
                pst.setString(8, txt_productname.getText());
                pst.setString(9, txt_unitprice.getText());
                pst.setString(10, txt_issuequantity.getText());
                //execute query
                pst.execute();
                //call current stock method
                // current_stock();

                JOptionPane.showMessageDialog(null, "Product Issue Success ");

                // String update = "update into product_info set quantity = '"+tem_quantity+"' where product_code = '"+product_code+"' ";
                //pst = conn.prepareStatement(update);
                //pst.execute();

                /*if( Integer.parseInt(p_qunatity) < Integer.parseInt(issue_quantity))
                {
                    JOptionPane.showMessageDialog(null, "Product is not Enough in store");
                }*/
                clear();

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            Update_table();

        }
    }//GEN-LAST:event_cmd_product_issueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         MessageFormat header = new MessageFormat("Product Issue TO Branch Information");
         MessageFormat footer = new MessageFormat("page{0,number,integer}");
        
        try
        {
            product_issue_table.print(JTable.PrintMode.NORMAL, header, footer);
            
        }catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %s%n ", e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void current_stock()
    {
        String p_code = txt_productcode.getText();
        String quantity = txt_issuequantity.getText();
        try
        {
            String update = "update product_info set quantity = quantity - ? where product_code = ? ";
            conn.setAutoCommit(false);
            pst = conn.prepareStatement(update);
            pst.setString(1, txt_productcode.getText());
            pst.setInt(2, Integer.parseInt(quantity));
            pst.execute();
            
            int rows = pst.executeUpdate();
           
            // call productInfoJframe value
            // ProductInfoJFrame pf = new ProductInfoJFrame();
            
            
                    
            if(rows > 0)
            {
                JOptionPane.showMessageDialog(this, "Product Issues Successfull");
            }else
            {
                JOptionPane.showMessageDialog(this, "Product Can not be issues successfull");
            }
         
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductIssueToBranchInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductIssueToBranchInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductIssueToBranchInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductIssueToBranchInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductIssueToBranchInfoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_back;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_product_issue;
    private javax.swing.JButton cmd_show_issue_product;
    private javax.swing.JButton cmd_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable product_issue_table;
    private javax.swing.JTextField txt_issue_from_address;
    private javax.swing.JTextField txt_issue_to_address;
    private com.toedter.calendar.JDateChooser txt_issuedate;
    private javax.swing.JTextField txt_issuefrom;
    private javax.swing.JTextField txt_issueno;
    private javax.swing.JTextField txt_issuequantity;
    private javax.swing.JTextField txt_issueto;
    private javax.swing.JTextField txt_productcode;
    private javax.swing.JTextField txt_productname;
    private javax.swing.JTextField txt_unitprice;
    // End of variables declaration//GEN-END:variables
}
